# Generated by Django 6.0.6 on 2026-07-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='ideas.productidea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
